### ISSUE TITLE
Running on Google Cloud Shell

### ISSUE THREAD

**Issue by opticoax747** [f8al/DNSrazzle#10]
python3 DNSrazzle.py
Traceback (most recent call last):
  File "DNSrazzle.py", line 41, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

Throwing an error

**Comment by f8al** [comment]
I haven't tried DNSRazzle on google cloud shell.  I know it works in AWS.  did you pip3 install the requirements.txt?  from what little I can see here this looks like the selenium web driver is not installed
