### ISSUE TITLE
Webdriver Github Auth

### ISSUE THREAD

**Issue by popcornhax** [f8al/DNSrazzle#11]
Kept running into rate limiting by github which is an issue with the Webdriver I guess.   I don't exactly understand why Webdriver has to download from github for each request, but I haven't looked too deeply yet.  

Found the config fix outlined under Configuration here:
https://github.com/SergeyPirogov/webdriver_manager#configuration

Not sure if this is something you might want to address in docs or in code but it can be a blocker for fresh installs.

**Comment by heller** [comment]
I believe this is fixed, but please let us know if there's more to be done. Thanks Dan!

**Comment by f8al** [comment]
closing with lack of comment
